version: '3.4'

services:
  digivisio2030.api:
    image: ${DOCKER_REGISTRY-}digivisio2030api
    build:
      context: .
      dockerfile: API/src/Dockerfile

  digivisio2030.ui:
    image: ${DOCKER_REGISTRY-}digivisio2030ui
    build:
      context: .
      dockerfile: UI/src/Dockerfile